tosca_definitions_version: tosca_simple_yaml_1_0

metadata:
  template_name: MAAS
  template_author: Quali
  template_version: 1.0.0
  template_icon: shell-icon.png

description: >
  sample deployment path file

imports:
  - cloudshell_standard: cloudshell_cloud_provider_standard_1_0_0.yaml

node_types:
  vendor.resource.MAAS Machine 2G:
    derived_from: cloudshell.nodes.CustomDeploymentOption
    properties:
      Operation System:
        type: string
        description: "The operating system to be installed on the machine. For example: 'Ubuntu'"
        tags: [user_input]
      Distribution:
        type: string
        description: "The distribution version of the operating system to be installed on the machine. For example: 'Bionic'"
        tags: [user_input]
      CPU Cores:
        type: integer
        default: 4
        tags: [user_input]
      RAM GiB:
        type: integer
        default: 16
        tags: [user_input]
      Disks:
        type: integer
        default: 1
        tags: [user_input]
      Storage GB:
        default: 512
        type: integer
        tags: [user_input]
    artifacts:
      icon:
        file: shell-icon.png
        type: tosca.artifacts.File